### ISSUE TITLE
Help need for running the project locally

### ISSUE THREAD

**Issue by amaljosea** [Gregor-Mendel-Institute/TRG-ImageProcessing#81]
Hello team, 

Thanks @gregormendelinstitute and @MiroslavPolacek for open-sourcing this project and the documentation.

I am new to AI and ML, would be great if someone could help me run this project. I have tried running the project on an Ubuntu laptop and on an AWS ec2 instance but I am getting some errors as explained below.

Below are my os/system specifications:

**Ubuntu desktop:**
<img src="https://github.com/Gregor-Mendel-Institute/TRG-ImageProcessing/assets/26934320/3a5b1c1c-1c76-4039-a8e1-dbfb858ea76f" width="500">

**AWS ec2 instance:**
<img width="500" alt="Screenshot 2023-11-16 at 11 58 28 PM" src="https://github.com/Gregor-Mendel-Institute/TRG-ImageProcessing/assets/26934320/79aec365-2ec1-42e9-b024-cbaa1f600b49">

This is the output I get: 

```
ubuntu@ip-172-31-7-148:~/dendro$ ls
image-processing_master.sif  images  out  singularity-ce-4.0.1-1.el7.x86_64.rpm  singularity-ce_4.0.1-2_amd64.deb
ubuntu@ip-172-31-7-148:~/dendro$ cd images/
ubuntu@ip-172-31-7-148:~/dendro/images$ ls
test.tiff
ubuntu@ip-172-31-7-148:~/dendro/images$ cd ..
ubuntu@ip-172-31-7-148:~/dendro$ singularity run --nv image-processing_master.sif --dpi=4800 --run_ID=0 --input=/home/ubuntu/dendro/images --output_folder=/home/ubuntu/dendro/out
WARNING: Could not find any nv files on this host!
WARNING: Could not find any nv libraries on this host!
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
/home/ubuntu

Configurations:
BACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     4
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0
DETECTION_NMS_THRESHOLD        0.3
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 4
IMAGE_CHANNEL_COUNT            3
IMAGE_MAX_DIM                  1024
IMAGE_META_SIZE                14
IMAGE_MIN_DIM                  800
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 2.0}
MASK_POOL_SIZE                 14
MASK_SHAPE                     [28, 28]
MAX_GT_INSTANCES               100
MEAN_PIXEL                     [123.7 116.8 103.9]
MINI_MASK_SHAPE                (56, 56)
NAME                           RetrainedRings
NUM_CLASSES                    2
POOL_SIZE                      7
POST_NMS_ROIS_INFERENCE        1000
POST_NMS_ROIS_TRAINING         2000
PRE_NMS_LIMIT                  6000
ROI_POSITIVE_RATIO             0.33
RPN_ANCHOR_RATIOS              [0.5, 1, 2]
RPN_ANCHOR_SCALES              (32, 64, 128, 256, 512)
RPN_ANCHOR_STRIDE              1
RPN_BBOX_STD_DEV               [0.1 0.1 0.2 0.2]
RPN_NMS_THRESHOLD              0.9
RPN_TRAIN_ANCHORS_PER_IMAGE    256
STEPS_PER_EPOCH                1
TOP_DOWN_PYRAMID_SIZE          256
TRAIN_BN                       False
TRAIN_ROIS_PER_IMAGE           200
USE_MINI_MASK                  True
USE_RPN_ROIS                   True
VALIDATION_STEPS               1
WEIGHT_DECAY                   0.0001


Traceback (most recent call last):
  File "/home/mambauser/postprocessing/postprocessingCracksRings.py", line 112, in <module>
    from training.prepareAnnotations import prepareAnnotations
  File "/home/mambauser/training/prepareAnnotations.py", line 9, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'

```

Help needed here:
- Not sure on how to fix `ModuleNotFoundError: No module named 'lxml'`

Notes:
- When the `--nv` flag is removed the first two warnings are gone, but getting the same rest of the output.
- test.tiff is a copy of [this](https://github.com/Gregor-Mendel-Institute/TRG-ImageProcessing/blob/master/CoreProcessingPipelineScripts/CNN/Mask_RCNN/training/sample_dataset/train/1350_00041008a_0_pSX1.965402638101432_pSY1.9654116736824034.tif) I converted to tiff using https://cloudconvert.com/tif-to-tiff
- Not sure if this is the issue with my low system specifications.
- I used this method to setup singularity in my machines https://github.com/apptainer/singularity/issues/5390#issuecomment-899111181

Questions:
- Will this work on docker? or singularity is necessary. 

Any help will be highly appreciated.

I am interested to contribute to the repo in the future.

Thanks and regards
Amal

**Comment by amaljosea** [comment]
I was able to run the project locally.

Few learnings:
- I used docker to build a new image by adding the missing dependencies `lxml` and `libiconv`.
- I built the new docker image in the Ubuntu desktop system with the configuration mentioned in the above comment.
- The building of the docker image was not working on Mac because Micromamba requires Linux.
- `weightRing` looks like a required field.
- I was not able to access the local files in the system, so I ended up creating the input and output folder inside the docker image.
